USE bundesliga;

CREATE TABLE team_match_stats (
	WS_id_primary_key VARCHAR (50) PRIMARY KEY,
	match_id INT NOT NULL, 
	Team_Code INT NOT NULL, 
    Team_result	VARCHAR (50),
    Team_points	INT,
    Team_Goals	INT NOT NULL, 
    Opp_Goals	INT NOT NULL, 
    HTorAT VARCHAR (30) NOT NULL,
    manager VARCHAR (100),

	Shots INT,
	Shots_on_target INT,
	Pass_Success_percent INT,
	Aerial_Duel_Success_percent INT,
	Dribbles_won INT,
	Tackles INT,
	Possession_percent INT,
	Total_Attempts INT,
	Goals INT,
	Conversion_Rate_percent INT,
	Open_Play_shots INT,
	Set_Piece_shots INT,
	Counter_Attack_shots INT,
	Penalty_shots INT,
	Own_Goal_shots INT,
	Total_Passes INT,
	Crosses INT,
	Through_Balls INT,
	Long_Balls INT,
	Short_Passes INT,
	Average_Pass_Streak INT,
	Total_Cards INT,
	Cards_for_Fouls INT,
	Cards_for_Unprofessional INT,
	Cards_for_Dives INT,
	Cards_for_Other INT,
	Red_Cards INT,
	Yellow_Cards INT,
	Cards_per_Foul_percent INT,
	Fouls_per_Game INT,
	Ratings FLOAT,
	Total_Shots INT,
	Woodwork_shots INT,
	Shots_on_target_B INT,
	Shots_off_target INT,
	Shots_blocked INT,
	Possession_percent_b INT,
	Touches INT,
	Pass_Success_percent_b INT,
	Total_passes_b INT,
	Accurate_passes INT,
	Key_passes INT,
	Dribbles_Won_b INT,
	Dribbles_attempted INT,
	Dribbled_past INT,
	Dribble_Success_percent INT,
	Aerials_Won INT,
	Aerials_Won_percent INT,
	Offensive_Aerials INT,
	Defensive_Aerials INT,
	Successful_Tackles INT,
	Tackles_Attempted INT,
	Was_Dribbled INT,
	Tackle_Success_percent INT,
	Clearances INT,
	Interceptions INT,
	Corners INT,
	Corner_Accuracy_percent INT,
	Dispossessed INT,
	`Errors` INT,
	Fouls INT,
	Offsides INT,
	Goals_b INT,
	Shots_on_Target_c INT,
	Shots_off_Target_b INT,
	Woodworks_shots INT,
	Blocked_shots INT,
	Own_shots INT,
	`6_yard_box_shots` INT,
	Penalty_Area_shots INT,
	Outside_of_box_shots INT,
	Open_Play_shots_b INT,
	Fastbreak_shots_b INT,
	Set_Pieces_shots_b INT,
	Penalty_shots_b INT,
	Own_Goal_shots_b INT,
	Right_foot_shots INT,
	Left_foot_shots INT,
	Headed_shots INT,
	Crossed_passes INT,
	Freekick_passes INT,
	Corner_passes INT,
	Through_Balls_b INT,
	Throw_Ins INT,
	Key_Passes_b INT,
	Long_passes_b INT,
	Short_passes_b INT,
	Chipped_passes INT,
	Ground_passes INT,
	Headed_passes INT,
	Feet_passes INT,
	Forward_passes INT,
	Backward_passes INT,
	Passes_to_Left INT,
	Passes_to_Right INT,
	Defensive_Third_passes INT,
	Mid_Third_passes INT,
	Final_Third_passes INT,
	Successful_passes_b INT,
	Unsuccessful_passes_b INT,
	Successful_Tackles_b INT,
	Was_Dribbled_b INT,
	Interceptions_b INT,
	Total_clearances INT,
	clearances_Off_The_Line INT,
	clearances_with_Head INT,
	clearances_with_Feet INT,
	Blocked_Shots_c INT,
	blocked_Crosses INT,
	Offsides_b INT,
	Fouls_b INT,
	Aerial_duels_b INT,
	Touches_b INT,
	Dispossessed_b INT,
	Turnover INT,
	error_Lead_to_Shot INT,
	error_Lead_to_Goal INT,
	Saves INT,
	Claims INT,
	Punches INT,
    
    FOREIGN KEY (match_id) references matches(WS_match_id),
    FOREIGN KEY	(Team_Code) references teams(team_code)
);
